[package]
name = "h-schroedinger"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.35.0"
bevy_egui = "0.38.0"
bevy_pancam = { version = "0.19.0", features = ["bevy_egui"] }
